config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  concern :commentable do |options|
    resources :comments, options
  end

  resources :articles do
    concerns :commentable, commentable_type: 'Article'
  end

  resources :comments do
    concerns :commentable, commentable_type: 'Comment'
  end


  resources :tags
  root 'welcome#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  #belongs_to :article
  
  has_many :subcomments, class_name: "Comment", as: :commentable, dependent: :destroy
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable, only: [:create, :destroy, :new]
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
 
  # def create
  #   @article = Article.find(params[:article_id])
  #   @comment = @article.comments.create(comment_params)
  #   redirect_to @article
  # end
  def new 
    @comment = current_user.comments.build(commentable: @commentable)
  end 
  # def index
  #   @comment = Comment.all
  # end

  def create 
    @comment = current_user.comments.create!(commentable: @commentable, body: comment_params[:body])
    #redirect_to @article
    redirect_to articles_path
  end

  def destroy 
    if params[:commentable_type] == 'Article'
      @article = Article.find(params[:article_id])

      @comment = @article.comments.find(params[:id])
      @comment.destroy
    else
      @comment = Comment.find(params[:comment_id])
      @subcomment = @comment.subcomments.find(params[:id])
      @subcomment.destroy
    end
    #redirect_to @article
    redirect_to articles_path
  end 

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_commentable
      commentable_id = params["#{params[:commentable_type].underscore}_id"]
      @commentable = params[:commentable_type].constantize.find(commentable_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= User.find(comment.user_id).email %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p class="reply" >
  <% if comment.subcomments.exists? %>
    <% comment.subcomments.each do |comment| %>
      <p>
        <strong>reply:</strong>
        <%= comment.body %>
      |
        <strong>by:</strong>
        <%= User.find(comment.user_id).email %>
        <% if comment.user == current_user %>
          <%= link_to 'Destroy reply', [comment.commentable, comment],
                method: :delete,
                data: {confirm: 'Are you sure?'}
          %>
        <% end %>
      </p>
    <% end %>
  <% end %>
</p>

<p>
  <% if comment.user == current_user %>
    <%= link_to 'Destroy Comment', [comment.commentable, comment],
                method: :delete,
                data: {confirm: 'Are you sure?'}
    %>
  <% end %>
|
  <%= link_to 'Reply', new_comment_comment_path(comment) %>
</p>            

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  

app/views/comments/new.html.erb
<%= form_with(model: [@commentable, @comment.subcomments.build], local: true) do |form| %>
    

    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>
  