config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  concern :commentable do |options|
    resources :comments, options
  end

  resources :articles do
    concerns :commentable, commentable_type: 'Article'
  end

  resources :comments do
    concerns :commentable, commentable_type: 'Comment'
  end


  resources :tags
  root 'welcome#index'
end

app/models/article.rb
class Article < ApplicationRecord
  #has_many :comments, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  validates :title, presence: true,
                    length: {minimum: 2}
  belongs_to :user

  def tag_list
  #   self.tags.collect do |tag|
  #     tag.name
    tags.join(",")
  #   end.join(",")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  before_action :authenticate_user!, except: [:index, :show]
  #http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]
  def index
    @articles = Article.all.includes([:user])
  end

  def show 
    @article = Article.find(params[:id])
  end

  def new
    # @article = Article.new
    @article = current_user.articles.build
  end
  
  def edit
    @article = Article.find(params[:id])
  end

  def create
    #render plain: params[:article].inspect
    #@article = Article.new(params[:article])
    @article = current_user.articles.build(article_params)
    #@article = Article.new(article_params)
    if @article.save
      flash.notice = "Article '#{@article.title}' Created!"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash.notice = "Article '#{@article.title}' Updated!"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash.notice = "Article '#{@article.title}' Deleted!"
    redirect_to articles_path
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :text, :tag_list)
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %>
          : article not saved!
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
    
    <p>
      <%= form.label :tag_list %><br/>
      <%= form.text_field :tag_list %>
    </p>

    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<%= link_to '<Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New Article', new_article_path %>
<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>User</th>
        <th colspan="3"></th>
    </tr>

    <% @articles.each do |article| %>
      <tr>
          <td><%= article.title %> | </td>
          <td><%= article.text %> | </td>
          <td><%= article.user.email %> | </td>
          <td><%= link_to 'Show', article_path(article) %></td> 
          <% if article.user == current_user %>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article_path(article),
                    method: :delete,
                    data: {confirm: 'Are you sure?'} %>
          <% end %>
          </td>
          </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Artcle</h1>
<%= render 'form' %>

<%= link_to '<Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<% if @article.user == current_user %>
  <%= link_to 'Edit', edit_article_path(@article) %>
<% end %>
<%= link_to '<Back', articles_path %>